### ISSUE TITLE
Geiser history stops adding new entries after erroneous input

### ISSUE THREAD

**Issue by novemberist** [jaor/geiser#199] opened 2016-12-21 12:03 UTC
Hello, I'm using geiser-mode (latest version from melpa) with guile 2.0.13. However, every once in a while the history of the repl seems to break and no new entries will be added anymore, so i have to restart the repl and manually delete ~/.emacs.d/geiser-history.guile to get a fresh, working history again. (this file btw apparently only gets created once the repl buffer has been killed) 

I have tried to reproduce the issue several times and apparently it seems to be related to invalid/erroneous input into the repl. so once guile throws an error at me, the history will not take any new enties anymore. example:

```
scheme@(guile-user)> 1
$2 = 1
scheme@(guile-user)> 2
$3 = 2
scheme@(guile-user)> 3
$4 = 3

;;; the history still works at this point. M-p will correctly give me 3

scheme@(guile-user)> (print 'test)
;;; <stdin>:12:0: warning: possibly unbound variable `print'
<unnamed port>:12:0: In procedure #<procedure 24f8a80 at <current input>:12:0 ()>:
<unnamed port>:12:0: In procedure module-lookup: Unbound variable: print

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
scheme@(guile-user) [1]> 4
$5 = 4
scheme@(guile-user) [1]> 5
$6 = 5

;;; history is "broken" after the invalid input of (print 'hello) and stuck at that entry. M-p will only 
ever return (print 'hello) and no newer entries.
```

is this expected behavior (i.e. am I using geiser wrong in any way?) or can it be considered a bug?

**Comment by jaor** [comment] 2016-12-21 13:05
i cannot reproduce the behaviour you describe: here, even after the
error, the history is still fully traversable (as it should be). what
does happen is that inputs during debug mode are not saved in history
(that behaviour is controlled by the variable
geiser-repl-save-debugging-history-p, which is nil by default).

are you using any configuration expecific for geiser? what is your
operating system? once you enter the wrong status, if you quit the repl
and look at the history file (yes, it's only saved on quit on purpose),
do you see anything in it that looks wrong?

**Comment by sphakka** [comment] 2017-11-10 15:58
Same here: history recording stops at the first invalid input. I'm on:
- emacs v25.3 (Gentoo ebuild)
- Geiser 0.6 (or 20171102.1825)

Only the history file location was customized.

A sample history:
```
$ cat ~/.emacs.d/geiser-history.guile
'()
}{
'( 12 3)
}{
asfdsf
}{
'()
}{
(list 1 2)
}{
asfdsf
}{
(cons  1 2)
}{
'()
}{
(cons  1 2)
}{
asdasdasdfsd
}{
```
Note that after each bogus input (1st was `asfdsf`) I quit and restarted: items were recorded until the next bogus input -- here above you see the result of 3 sessions. In particular, it looks like var `geiser-repl-history-no-dups-p` (on) is not honored...

**Comment by jaor** [comment] 2017-11-11 21:27
@sphakka, when `geiser-repl-save-debugging-history-p` is nil (the
default), inputs in the REPL while guile is in the debugger prompt
(those that look like `scheme@(guile-user) [1]>`) are not saved in
history.

things should work as you expect if you set that variable to t.  is that
so?

**Comment by sphakka** [comment] 2017-11-12 15:09
Gotcha! Indeed, I didn't notice that the REPL had switched to debugging... oops. Yes toggling `geiser-repl-save-debugging-history-p` does the trick :-)
Thanks for the help.

**Comment by jaor** [comment] 2017-11-13 05:04
thanks for the feedback, @sphakka. i am closing this one!

**Closed by jaor** 2017-11-13 05:04 UTC
Labels: more information needed
