### ISSUE TITLE
Missing output when evaluating from a scheme buffer

### ISSUE THREAD

**Issue by alezost** [jaor/geiser#83] opened 2015-09-07 19:43 UTC
Hello, try the following recipe:

1. M-x run-guile

2. Make a scheme buffer, paste and evaluate the following code there:

   ```scheme
   (define bad-port (current-output-port))
   (define (message str) (display str bad-port))
   ```

3. Go to the REPL and run `(message "hello\n")` there.  There is no
   `hello` output!

Now reevaluate `bad-port` definiton, but this time do it in the REPL.
And if you rerun message again, the output will be there!

You may repeat: if `bad-port` definition is evaluated from a scheme
buffer, the output does not appear, but if it is evaluated in the REPL,
it does.

(I checked it only with Guile)

**Comment by dleslie** [comment] 2015-09-07 21:02
Could not reproduce with Chicken:

```scheme
#;1> (define bad-port (current-output-port))
#;7> (define (message str) (display str bad-port))
#;8> (message "Hello\n")
Hello
#;9> bad-port
#<output port "(stdout)">
```

Although, Chicken still has the hilarious numbering bug #58

**Comment by dleslie** [comment] 2015-09-07 21:05
It happens in Chicken, as well.

```scheme

#;1> (message "Hello\n")
#;7> (define bad-port (current-output-port))
#;8> (message "Hello\n")
Hello
```

Also, note that #58 is still present.

**Comment by dleslie** [comment] 2015-09-07 21:09
Interestingly, this seems port-specific. It doesn't have the same effect with other symbols bound at that scope but of other types.

**Comment by dleslie** [comment] 2015-09-07 21:11
Hmm.

In a chicken buffer:

```scheme
(define test-port (current-output-port))
(define (test-message) (display (->string test-port)))
```

Then in the REPL:
```scheme
#;1> (test-message)
#<output port "(string)">
```

This makes sense. Geiser is capturing the response to the eval to a string; what seems to be happening is that data written to stdout isn't also captured, or somesuch.

**Comment by dleslie** [comment] 2015-09-07 21:14
This is a tricky bug, because it involves binding ```current-output-port```; intuitively, it seems like the solution may have to be unhygienic. :disappointed:

**Comment by jaor** [comment] 2015-09-07 22:04
when you evaluate from a scheme buffer, `(current-output-port)` evaluates to a string port (if you eval it while in the buffer you get something like `<:output:string ...>`), which is being used by guile's geiser eval function to capture the result of the evaluation, format it, and send it back to emacs.  that's done during a parameterization.  once the evaluation is finished that port is gone.  if you go to the REPL, no redirection is in place, and assigning `bad-port` there just works as expected (if you eval `(current-ouput-port)` in the REPL you'll see it's something like `<output: file /dev/pts/4>`).

so this behaviour is more or less to be expected.  fixing it is non-trivial.

**Comment by dleslie** [comment] 2015-09-08 16:33
I was thinking about this a little more this morning, and it strikes me that this is a symptom of interpreting code that violates convention. ```current-output-port``` is not designed to return a consistent value, but rather it returns whatever port is presently associated with output at the time of invocation; what port that is when invoked at top level is determined by how the Scheme code is invoked. The appropriate use is to invoke ```(current-input-port)``` as late as possible, at the time of execution.

IE, I wouldn't expect ```bad-port``` to represent a consistent port when executed with ```csi``` versus when its compiled with ```csc``` or called as a library via ```load``` or ```compile-file```.

Now, I wonder what the behaviour for ```standard-output-port``` is?

http://www.scheme.com/tspl4/io.html#g124

**Comment by jaor** [comment] 2015-09-08 17:17
yes, i think i agree with dan here... the current output ports when
you're in the buffer and we are in the repl are simply different, and
one cannot expect them to be equal... perhaps there's a stronger case to
be made for current-output-port to be the same for all evaluations in a
buffer, but i'm not sure the implementation effort that guarantee would
entail is worth it...

**Comment by dleslie** [comment] 2015-09-08 19:09
It appears that ```standard-output-port``` is unavailable in Chicken.

I vote to close this. :smile:

**Comment by jaor** [comment] 2015-09-08 19:52
+1 :) what do you think, alex? do you have a use case in mind where it'd
be important to have a better behaviour?

**Comment by alezost** [comment] 2015-09-08 20:40
Yes, there is a use case in [GNU Guix](https://www.gnu.org/software/guix/).  We have `current-build-output-port` (http://git.savannah.gnu.org/cgit/guix.git/tree/guix/store.scm#n381) there.  And the problem is when `(use-modules ...)` clause is evaluated from a scheme buffer, this build output (which is highly important) disappears.

I opened this issue after facing this problem in Guix: http://lists.gnu.org/archive/html/guix-devel/2015-09/msg00130.html

So it would be really great if this could be solved, but I see that it's not easy.

**Comment by dleslie** [comment] 2015-09-08 20:54
Why not:

(define current-build-output-port
  ;; The port where build output is sent.
  (lambda () (current-error-port)))


Alex Kost <notifications@github.com> writes:

> Yes, there is a use case in [GNU Guix](https://www.gnu.org/software/guix/).  We have `current-build-output-port` (http://git.savannah.gnu.org/cgit/guix.git/tree/guix/store.scm#n381) there.  And the problem is when `(use-modules ...)` clause is evaluated from a scheme buffer, this build output (which is highly important) disappears.
>
> I opened this issue after facing this problem in Guix: http://lists.gnu.org/archive/html/guix-devel/2015-09/msg00130.html
>
> So it would be really great if this could be solved, but I see that it's not easy.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jaor/geiser/issues/83#issuecomment-138692936

-- 
-Dan Leslie

**Comment by dleslie** [comment] 2015-09-08 21:01
Why not:

```scheme
(define current-build-output-port
  ;; The port where build output is sent.
  (lambda () (current-error-port)))
```

**Comment by alezost** [comment] 2015-09-09 16:36
I guess that with a parameter, it will be bound to a single port.  While
if it's a procedure it may return different ports, because the error
port may change.  But thank you!  This is an interesting proposal, I'll
ask about it on guix mailing list.

**Comment by dleslie** [comment] 2015-09-09 16:47
It can be improved:

```scheme
(define current-build-output-port current-error-port)
```

**Comment by alezost** [comment] 2015-09-09 16:48
Sure, I understand :smile:

**Comment by dleslie** [comment] 2015-10-14 00:29
Can we close this issue, @jaor ?

**Comment by jaor** [comment] 2015-10-14 00:58
what do you think, @alezost ? if guix can solve this issue by its own means, it'll save us lots of headaches :)

**Comment by alezost** [comment] 2015-10-14 12:57
Oh yes, sorry I forgot about this one.  We have a workaround for this in Guix, so I don't mind if it will be closed, thanks.

**Closed** 2015-10-14 15:14 UTC

**Comment by Apteryks** [comment] 2017-10-09 22:10
Hello, I stumble on this issue today. It took me a couple hours figuring out what was at cause and doing the background research. That this bug was closed didn't help :).

In my case, simply re-evaluating a Scheme buffer twice leads to missing output. My repro is not as trivial as the one of @alezost, but I hope it can show a representative use case:

````scheme
;;; REPRO STEPS:
;;;
;;; 0. C-z to start the Geiser's Guile REPL.
;;;
;;; 1. C-c C-b to evaluate once. You should see in the output:
;;;
;;;   => #t
;;;
;;;   current-warning-port: #<output: string 255fc40>
;;;   guix-warning-port: #<output: string 255fc40>
;;;   current-error-port: #<output: string 255fc40>
;;;   current-build-output-port: #<output: string 255fc40>
;;;   error: bad-arg: unrecognized option
;;;   Caught exception: (quit 1)
;;;
;;; Notice the error output: error: check: unrecognized option
;;;
;;; 2. C-c C-b again. Now the error output is gone:
;;;
;;;   
;;;   => #t
;;;   
;;;   current-warning-port: #<output: string 481ab60>
;;;   guix-warning-port: #<output: string 255fc40>
;;;   current-error-port: #<output: string 481ab60>
;;;   current-build-output-port: #<output: string 255fc40>
;;;   Caught exception: (quit 1)

(use-modules (gnu packages)
	     (gnu packages version-control)
	     (guix download)
	     (guix packages)
	     (guix scripts download)
	     (guix store)
	     (guix ui))

(define (check-package-source package)
  "Fetch the archive of a package.  Assumes the definition of PACKAGE
contains an origin using the url-fetch method."
  (catch #t
    (lambda ()
      (guix-download "--bad-arg" (origin-uri (package-source package))))
    (lambda (arg . rest)
      (format #t "Caught exception: ~a~%" (cons arg rest)))))

(format #t "current-warning-port: ~a~%" (current-warning-port))
(format #t "guix-warning-port: ~a~%" (guix-warning-port))
(format #t "current-error-port: ~a~%" (current-error-port))
(format #t "current-build-output-port: ~a~%" (current-build-output-port))

(check-package-source libgit2)
````
I discussed the issue in #guile but the solutions discussed above (such as making `current-build-output-port` a procedure) were not deemed adequate. In Guile at least, `current-error-port`) is a SRFI-39 parameter, just like `current-build-output-port` in Guix. Both are set to an initial value.
