### ISSUE TITLE
Geiser's `eval-last-sexp` doesn't give any useful error messages on failure

### ISSUE THREAD

**Issue by jaseemabid** [jaor/geiser#219] opened 2017-09-07 17:01 UTC
Evaluating an undefined variable or a syntax error doesn't give any error messages at all. Loading the same in the repl behaves as expected. 

I'm using version `20170704.1044` from elpa. Emacs 25.2.1 with Spacemacs. Petize Chez 9.4.1

**Comment by ChaosEternal** [comment] 2017-09-08 09:08
I think my last pr fixes this.

**Comment by jaor** [comment] 2017-09-09 00:15
what scheme? how are you starting geiser? have you an example of what
you are evaluating? how are you evaluating it (what keyboard shortcut,
if any)? what do you see in the log buffer that pops-up after
`C-u M-x geiser-show-logs` (and the perform the evaluation)?  does
evaluating a valid expression work?

thanks.

**Comment by jaseemabid** [comment] 2017-09-11 06:04
- Chez 9.4.1
- I use `C-c C-z` to start the repl usually , bound to `switch-to-geiser`
- Example I'm evaluating `(+ 1 1)`, I see `=> 2` in the modeline. Evaluate `(+ 1 a)` without defining a, I see nothing in the modeline. No error is reported. I use `geiser-eval-last-sexp` for this bound to `, e e` (spacemacs).
- This is what I have in the logs.

```
INFO: REQUEST: <1>: (begin (import (geiser)) (write `((result ) (output . ""))) (newline))
INFO: RETORT: ((result) (output . ""))
INFO: <1>: processed
```

**Comment by jaseemabid** [comment] 2017-09-11 06:20
M-x `geiser-version` says `@PACKAGE_STRING@`. But I see `(define-package "geiser" "20170827.1755")` in geiser-pkg.el.

**Comment by ChaosEternal** [comment] 2017-09-11 08:11
I have tested and reproduced the problem. should be a bug. I will fix it.

**Comment by jaseemabid** [comment] 2017-09-11 09:16
@ChaosEternal I notice the same behaviour. Echoing the output to minibuffer on success as well as failure is probably what we need.

**Comment by ChaosEternal** [comment] 2017-09-12 08:51
I think I cannot just simply patch the geiser-mode.el since it is a chez specific problem.
I guess the root cause is that the geiser-chez.el does not have display-error defined.

**Comment by ChaosEternal** [comment] 2017-09-12 16:46
After comparing geiser-chez.el and geiser-guile.el, I am now pretty sure that lack of display-error in geiser-chez.el is the root cause.
Finding out the root cause is one thing, but fixing it is a big story.
I need to investigate how error handling and debugging work in geiser and maybe it is needed to complete the geiser-chez.el.
keep tuned. 

for a quick  fix, 
use this patch:
modified   elisp/geiser-chez.el
@@ -103,6 +103,11 @@ This function uses `geiser-chez-init-file' if it exists."
     (compilation-setup t)
     (geiser-eval--send/wait "(begin (import (geiser)) (write `((result ) (output . \"\"))) (newline))")))
 
+
+(defun geiser-chez--display-error (module key msg)
+  (and key (message key) key))
+
+
 ;;; Implementation definition:
 
 (define-geiser-implementation chez
@@ -120,7 +125,7 @@ This function uses `geiser-chez-init-file' if it exists."
   (exit-command geiser-chez--exit-command)
   (import-command geiser-chez--import-command)
   (find-symbol-begin geiser-chez--symbol-begin)
-  ;; (display-error geiser-chez--display-error)
+  (display-error geiser-chez--display-error)
   ;; (external-help geiser-chez--manual-look-up)
   ;; (check-buffer geiser-chez--guess)
   ;; (keywords geiser-chez--keywords)

**Comment by ChaosEternal** [comment] 2017-09-13 05:32
```
@@ -103,6 +103,11 @@ This function uses `geiser-chez-init-file' if it exists."
     (compilation-setup t)
     (geiser-eval--send/wait "(begin (import (geiser)) (write `((result ) (output . \"\"))) (newline))")))
 
+
+(defun geiser-chez--display-error (module key msg)
+  (and key (message key) key))
+
+
 ;;; Implementation definition:
 
 (define-geiser-implementation chez
@@ -120,7 +125,7 @@ This function uses `geiser-chez-init-file' if it exists."
   (exit-command geiser-chez--exit-command)
   (import-command geiser-chez--import-command)
   (find-symbol-begin geiser-chez--symbol-begin)
-  ;; (display-error geiser-chez--display-error)
+  (display-error geiser-chez--display-error)
   ;; (external-help geiser-chez--manual-look-up)
   ;; (check-buffer geiser-chez--guess)
   ;; (keywords geiser-chez--keywords)


```

**Comment by ChaosEternal** [comment] 2017-09-13 14:05
@jaseemabid use the patch in PR #220 , this version avoids a geiser-debug window from opening.

**Comment by ChaosEternal** [comment] 2017-09-13 14:16
@jaor with PR #220 , I think this issue is resolved. I suggest we close this issue and open another feature requesting issue addressing the debug functionality of chezscheme support.

**Closed** 2017-09-13 23:03 UTC
