### ISSUE TITLE
Guiser not work with #lang plai-typed

### ISSUE THREAD

**Issue by qiuwei** [jaor/geiser#171] opened 2016-08-23 21:50 UTC
When using geiser-mode with a racket file with the language declaration "#lang 
plai-typed", a call to geiser-eval-buffer treats the buffer as if there had 
been a language declaration "#lang plai".

geiser-compile-current-buffer works fine.

**Comment by ntdef** [comment] 2016-10-12 20:37
This is definitely a duplicate of #2. You might want to check the thread there. However the bug is still an open issue.

**Comment by jaor** [comment] 2018-06-10 19:10
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/171

**Closed by jaor** 2018-06-10 19:10 UTC
