### ISSUE TITLE
Empty input in Chicken REPL causes error

### ISSUE THREAD

**Issue by fice-t** [jaor/geiser#154] opened 2016-06-02 05:54 UTC
Just pressing "RET" at the prompt gives off the error:

```
Error: unbound variable: geiser-no-values

	Call history:

	<syntax>	  (geiser-no-values)
	<eval>	  (geiser-no-values)	<--
```

This doesn't happen with Guile.

**Comment by paines** [comment] 2016-08-06 07:26
I finally figured out what the problem is I think. I we take a look at ...scheme/chicken/geiser/emacs.scm we see a list of modules which needs to be loaded by chicken like:
```
 (use
    apropos
    chicken-doc
    data-structures
    extras
    ports
    posix
    srfi-1
    srfi-13
    srfi-14
    srfi-18
    srfi-69
    tcp
    utils)
```
I was missing at least 2, apropos and chicken-doc. Install those via chicken-install -s apropos etc... from command line. Additionally add to emacs config 
```
(require 'geiser)
(setq geiser-chicken-compile-geiser-p nil)
```

**Comment by dleslie** [comment] 2016-08-06 14:27
Thanks for following up! I've been swamped with work lately.

For future reference for anyone who finds this bug; in the docs:

```
** Chicken Addendum
    These steps are necessary to fully support Chicken Scheme, but are
    not required for any other scheme.

    - Install the necessary support eggs:
      $ chicken-install -s apropos chicken-doc
    - Update the Chicken documentation database:
      $ cd `csi -p '(chicken-home)'`
      $ curl http://3e8.org/pub/chicken-doc/chicken-doc-repo.tgz | sudo tar zx
```

:smile:

**Comment by dleslie** [comment] 2016-08-06 14:27
Chicken really should warn in a meaningful way rather than fail poorly.

**Comment by fice-t** [comment] 2016-08-06 17:59
I didn't need the `(setq geiser-chicken-compile-geiser-p nil)` to work, but installing `chicken-doc` did indeed work, thanks.

I was under the assumption that the extra Chicken work was only needed for Geiser's autodoc, not other functionality as well. It might be nice to state what exactly doesn't work out of the box in the documentation.

Though I'm not sure why I would need `chicken-doc` for either this issue or #151. I changed the call to `geiser-no-values` in `geiser-chicken` to `values` and it worked fine, for instance.

**Comment by dleslie** [comment] 2016-08-06 18:02
Patches are welcome :)                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: fice-tSent: Saturday, August 6, 2016 10:59 AMTo: jaor/geiserReply To: jaor/geiserCc: Dan Leslie; AssignSubject: Re: [jaor/geiser] Empty input in Chicken REPL causes error (#154)I didn't need the (setq geiser-chicken-compile-geiser-p nil) to work, but installing chicken-doc did indeed work, thanks.

I was under the assumption that the extra Chicken work was only needed for Geiser's autodoc, not other functionality as well. It might be nice to state what exactly doesn't work out of the box in the documentation.

Though I'm not sure why I would need chicken-doc for either this issue or #151. I changed the call to geiser-no-values in geiser-chicken to values and it worked fine, for instance.

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jaor/geiser","title":"jaor/geiser","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jaor/geiser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fice-t in #154: I didn't need the `(setq geiser-chicken-compile-geiser-p nil)` to work, but installing `chicken-doc` did indeed work, thanks.\r\n\r\nI was under the assumption that the extra Chicken work was only needed for Geiser's autodoc, not other functionality as well. It might be nice to state what exactly doesn't work out of the box in the documentation.\r\n\r\nThough I'm not sure why I would need `chicken-doc` for either this issue or #151. I changed the call to `geiser-no-values` in `geiser-chicken` to `values` and it worked fine, for instance."}],"action":{"name":"View Issue","url":"https://github.com/jaor/geiser/issues/154#issuecomment-238036779"}}}

**Comment by fice-t** [comment] 2016-08-10 20:12
@dleslie I could, but I was thinking that since all the other Scheme implementations use a `geiser-no-values` then Chicken might as well.

Though why is `chicken-doc` required to export the functions `geiser-eval`, `geiser-no-values`, etc.? Why doesn't the normal module export work? It just seems odd to me.

**Comment by dleslie** [comment] 2016-08-10 23:42
It's because the entire module fails to load as a result of the unbound symbols. Chicken just says "Nope, I refuse to load this entire unit."

Anyhow, I have a patch inbound to make this a little more user-friendly.

**Comment by dleslie** [comment] 2016-08-11 22:43
@fice-t Chicken will now fail to run the REPL if the necessary modules are not installed; and will show an error in the Emacs REPL display to that effect.

`apropos` and `chicken-doc` are necessary for providing completions and el-doc support for installed and available eggs, and so cannot be removed without crippling Chicken's Geiser support or making changes to Chicken itself.

I am going to close this issue. Thanks for the feedback and bug report!

**Closed by dleslie** 2016-08-11 22:43 UTC
Labels: chicken
